### ISSUE TITLE
This repo is big

### ISSUE THREAD

**Issue by enocom** [StediInc/cdk-clj#41]
```
$ du -d 1 -h
 12K	./test
4.0K	./bin
 20K	./example-app
 19M	./resources
8.0K	./lambda
 80M	./.git
 40K	./src
100M	.
```

We should explore alternatives to committing CDK artifacts, as after just a few version upgrades we already have ~80MB in the git history.

**Comment by tvanhens** [comment]
Marc brought up the same issue in a different context. Bundling all these packages together means you can't opt into specific versions if there are breaking changes, you are forced to adopt everything wholesale. One option would be to just not bundle the jsii packages at all and use the mvn versions that are pushed as a part of aws cdk. The downside to these is that they contain generated java code bloat (which probably doesn't matter since this is a dev time dependency) and you would have to require individual modules manually in consumer projects.

**Comment by enocom** [comment]
The primary concern is to ensure that pulling this repo is fast (e.g., in a pipeline context). Maybe a little bloat is OK. Especially if it keeps the repo small on disk.

**Comment by tvanhens** [comment]
If the other tradeoff is alright (having to explicitly include modules in deps.edn) then this should be an easy change. We can just remove the included modules and update the docs pointing to the maven coords for modules. Will be a breaking change for consumers.

**Comment by enocom** [comment]
The README leaves some room for such changes. If the actual change included some hand-holding on how to overcome the breakage, it wouldn't be so bad IMHO.
